### ISSUE TITLE
Comparison to react-forms

### ISSUE THREAD

**Issue by natew** [insin/newforms#47]
I know this isn't an issue, but just saw this repo and I'm curious if you could clarify some differences with [react-forms](https://github.com/prometheusresearch/react-forms).

**Comment by insin** [comment]
I haven't used react-forms yet, but it looks like it does a bunch of things better than newforms out of the box:
- immutable state by default - win!
- `value`/`onChange` protocol React components for rendering - very easy to write and understand versus newforms widget classes
- lists of things are handled very easily as part of its schema definition
- it looks much easier to get started with and to customise with custom schema types and widgets in comparison to newforms, where you will end up referencing the built-in types heavily and the interplay between Fields and Widgets can get confusing

Perhaps we could ping @AndrewIngram here for pros and cons from experience - he's used both!

**Comment by AndrewIngram** [comment]
My general experience is that newforms is easier to understand, because it's familiar to someone with a Django background (ie me). But I think a lot of the beauty of Django's API is lost when using JavaScript syntax. It also suffers a bit from the fact that it existed before it was ported to React, so there's some oddities that don't feel entirely necessary.

With react-forms you define your schema, set it as a property of the library's Form component and it "just works", with newforms you have to do a bit of juggling when it comes to instantiating forms and state management, so it's not quite as elegant.

react-form's promises of easy custom components isn't entirely fulfilled yet, you still have to litter your schema definitions with component overrides if you want control over individual fields. And defining custom components is still fairly verbose. It also feels more geared towards giving you access to a JSON representation of data, rather than allowing the form itself to be submitted as rendered.

**Comment by insin** [comment]
Thanks @AndrewIngram.

I'm starting to work on moving form-level rendering out into React components, which will be an opportunity to hide the state management and provide a place to work towards a default `shouldComponentUpdate()` implementation for people who just need to render their fields as a flat list of components.

Any pointers on what some of the other oddities are? This is feedback gold, Jerry!

**Comment by AndrewIngram** [comment]
The other challenge I remember having was related to dynamically changing a form's fields. As forms become increasingly interactive, there's an increasing need to change entire sections on the form based on the values a user selects for certain fields (you can see an example if you click the enquiries link at the top of http://www.onefinestay.com/). My approach with newforms was to have multiple subclasses of a base form, and swap in the correct one when as changes are made, but this was a cumbersome way of doing it.

With react-forms, I can have my schema generated dynamically based on a state object (in my case, a Fluxxor store), as long as the parent component of the form listens to state changes to the store and re-renders, any updates to the schema get correctly applied without any extra work. And I actually find that changing the underlying schema allows for some interesting validation strategies. Rather than saying "if the value of field a=foo and field b has a value, then validate field c" you just change your schema to say "only include field c if its data pre-requisites are met"
