### ISSUE TITLE
Add support for some HTML Input attributes 

### ISSUE THREAD

**Issue by hugooliveirad** [insin/newforms#62]
It would be very useful if newforms Field API supported some HTML attributes such as `placeholder` and `disabled`. There's any reason this isn't implemented?

**Comment by insin** [comment]
I have plans for `disabled` and `hidden`, as they affect validation/requiredness and skipping rendering. Eventually, I want to have a way to define rules for those to implement dynamic show/hide/enable/disable.

`placeholder` is purely about display, though. How about a new core `Field` property - `widgetAttrs` - which lets you provide additional attributes for the field's widget without having to completely override it? This could be what's returned by the base `Field.prototype.widgetAttrs()` instead of the current hardcoded empty object.

**Comment by hugooliveirad** [comment]
Yes, `widgetAttrs` property looks like a great way to do that. Having to completely override the widget to do such a simple thing like adding `placeholder` ou `class` is way too complex.

What attrs would we support? This object is merged with `NumberField.prototype.widgetAttrs()`? (Couldn't analyze the code enough).

Adding this would make it possible to add `data-` attributes too, although I couldn't find any use case for them inside React.

**Comment by insin** [comment]
It would support any attribute you care to pass :smile: 

Fields add any widget attributes they're going to provide here: https://github.com/insin/newforms/blob/7c25efbb1912e9fd6e12c4771d5521d0ac9f93c5/src/Field.js#L59

Then any attributes provided during rendering, or passed into BoundField when rendering are merged over the top of them here: https://github.com/insin/newforms/blob/7c25efbb1912e9fd6e12c4771d5521d0ac9f93c5/src/Widget.js#L55

This new core field property could also be the basis for allowing people to attach their own event handlers when creating istances of forms, for not much extra work... this could be a more interesting next release than I thought :+1:

**Comment by hugooliveirad** [comment]
So we could simply add

``` js
kwargs.widgetAttrs = kwargs.widgetAttrs || {};
object.extend(kwargs.widgetAttrs, widget.attrs, this.widgetAttrs(widget));
```

?

**Comment by hugooliveirad** [comment]
Awesome :+1:
