### ISSUE TITLE
Clear a form after submitting

### ISSUE THREAD

**Issue by xgrommx** [insin/newforms#65]
Hello @insin 

How can I clear my form after submitting?

**Comment by insin** [comment]
If you want to keep the same form instance and render to the same React component, you need to use 
[controlled components for input](http://newforms.readthedocs.org/en/latest/react_client.html#controlled-user-inputs) and you can then use [`form.reset()`](http://newforms.readthedocs.org/en/latest/forms_api.html#Form#reset) to set the `Form` object back to its initial state.

You can also create a new `Form` from scratch, but if you're not using [controlled components](http://facebook.github.io/react/docs/forms.html#controlled-components), this won't affect whats currently rendered by React - you would need to change the `key` prop of the component containing the rendered form, or any of its ancestors, in order to force React to throw the component away and render it again from scratch.

**Comment by xgrommx** [comment]
Thank you @insin. It's very helpful.
